### ISSUE TITLE
Korean/Japanese Translation of Docs

### ISSUE THREAD

**Issue by totuta** [OpenNMT/opennmt.github.io#13]
Hi,

I found that Korean/Japanese translation of documentations are not done yet. Only intro pages are translated. Can I contribute by translating remaining parts?

**Comment by kination** [comment]
I have same request with @totuta . How can I find translated ones?

**Comment by guillaumekln** [comment]
Hi,

Sorry we missed OP's question somehow.

Which documentation are referring? We have now a [dedicated portal](http://opennmt.net/OpenNMT/) for the advanced documentation, but we don't want to maintain multiple version of it.

**Comment by kination** [comment]
@guillaumekln 
Oh, I looked on http://opennmt.net/ . There were some translated data such as french, chinese, korean, etc., so I wonder if I could keep working on it.

**Comment by guillaumekln** [comment]
We chose to remove the translated versions of the website for simplicity. Thanks.
