### ISSUE TITLE
wrong pretrained model

### ISSUE THREAD

**Issue by k4r573n** [OpenNMT/opennmt.github.io#22]
The [model to translate from de to en](https://s3.amazonaws.com/opennmt-models/wmt-ende_l2-h1024-bpe32k_release.tar.gz) in file [opennmt.github.io/Models.md](https://github.com/OpenNMT/opennmt.github.io/blob/master/Models.md) produces a german output. But I expect an english one.

**Comment by guillaumekln** [comment]
Where does it say that it is an German to English model? The section clearly indicates "English-German Translation".

**Comment by k4r573n** [comment]
Yes, but first I tried the model and got after translation an unexpected result (see below) and second I guess **ende**  in the model name stands for en 2 de (wmt-ende_l2-h1024-bpe32k_release.tar.gz)

I use [CTranslate ](https://github.com/OpenNMT/CTranslate) to translate from german to english with the following comand

    MODEL_NAME=model_ref
    cd ~/OpenNMT/
    SOURCE=../data/validation/bsp.de-en.de
    mkdir -p ../data/$MODEL_NAME/validation
      
    tokenize --bpe_model ~/data/${MODEL_NAME}/train-ende.bpe32000 --mode aggressive --segment_case --joiner_annotate < ${SOURCE} > ${SOURCE}.${MODEL_NAME}.tok
    translate --model ~/data/${MODEL_NAME}/model-ende_epoch7_5.55_release.t7 --time --src ${SOURCE}.${MODEL_NAME}.tok --tgt ../data/$MODEL_NAME/validation/${SOURCE##*/}.tok.trans
    detokenize  < ../data/$MODEL_NAME/validation/${SOURCE##*/}.tok.trans > ../data/$MODEL_NAME/validation/${SOURCE##*/}.tok.trans.detok

but finally the result is german including translation errors.

**Comment by k4r573n** [comment]
sorry - you'r right its just en 2 de.
It was only in my mind - some month ago it was there... thanks for pointing it out
